### ISSUE TITLE
load_datasets?

### ISSUE THREAD

**Issue by Adim-a11y** [NCAR/tiegcmpy#1]
I've gone through the documentation and attempted to use your model. However, I'm facing an issue with identifying the specific path required to create datasets using the function ty.load_datasets(directory, dataset_filter). Could you please assist me with this? Thank you in advance.

**Comment by AnonNick** [comment]
Hi @Adim-a11y 
I've made a google colab that should give you an idea on how to go about using the tool. [Colab Link](https://colab.research.google.com/drive/12FItrDPxUkO53ehf0c7776qufue0a3rm?usp=sharing)
This is the tools for analysis of datasets generated by TIEGCM and not for creation of datasets. 
To build datasets go to the TIEGCM github [https://github.com/NCAR/tiegcm](https://github.com/NCAR/tiegcm)
